AFRICA = [
    ("What is the capital of Algeria?", "Algiers"),
    ("What is the capital of Angola?", "Luanda"),
    ("What is the capital of Benin?", "Porto-Novo", "Porto Novo"),
    ("What is the capital of Botswana?", "Gaborone"),
    ("What is the capital of Burkina Faso?", "Ouagadougou"),
    ("What is the capital of Burundi?", "Gitega"),
    ("What is the capital of Cameroon?", "Yaounde", "Yaoundé"),
    ("What is the capital of Cape Verde?", "Praia"),
    ("What is the capital of the Central African Republic?", "Bangui"),
    ("What is the capital of Chad?", "NDjamena", "N'Djamena"),
    ("What is the capital of Comoros?", "Moroni"),
    ("What is the capital of the Democratic Republic of the Congo?", "Kinshasa"),
    ("What is the capital of the Republic of the Congo?", "Brazzaville"),
    ("What is the capital of Djibouti?", "Djibouti"),
    ("What is the capital of Egypt?", "Cairo"),
    ("What is the capital of Equatorial Guinea?", "Malabo"),
    ("What is the capital of Eritrea?", "Asmara"),
    ("What is the capital of Eswatini?", "Mbabane"),
    ("What is the capital of Ethiopia?", "Addis Ababa"),
    ("What is the capital of Gabon?", "Libreville"),
    ("What is the capital of Gambia?", "Banjul"),
    ("What is the capital of Ghana?", "Accra"),
    ("What is the capital of Guinea?", "Conakry"),
    ("What is the capital of Guinea-Bissau?", "Bissau"),
    ("What is the capital of Ivory Coast?", "Yamoussoukro"),
    ("What is the capital of Kenya?", "Nairobi"),
    ("What is the capital of Lesotho?", "Maseru"),
    ("What is the capital of Liberia?", "Monrovia"),
    ("What is the capital of Libya?", "Tripoli"),
    ("What is the capital of Madagascar?", "Antananarivo"),
    ("What is the capital of Malawi?", "Lilongwe"),
    ("What is the capital of Mali?", "Bamako"),
    ("What is the capital of Mauritania?", "Nouakchott"),
    ("What is the capital of Mauritius?", "Port Louis"),
    ("What is the capital of Morocco?", "Rabat"),
    ("What is the capital of Mozambique?", "Maputo"),
    ("What is the capital of Namibia?", "Windhoek"),
    ("What is the capital of Niger?", "Niamey"),
    ("What is the capital of Nigeria?", "Abuja"),
    ("What is the capital of Rwanda?", "Kigali"),
    ("What is the capital of Sao Tome and Principe?", "Sao Tome", "São Tomé"),
    ("What is the capital of Senegal?", "Dakar"),
    ("What is the capital of Seychelles?", "Victoria"),
    ("What is the capital of Sierra Leone?", "Freetown"),
    ("What is the capital of Somalia?", "Mogadishu"),
    ("What is the capital of South Africa?", "Pretoria", "Cape Town", "Bloemfontein"),
    ("What is the capital of South Sudan?", "Juba"),
    ("What is the capital of Sudan?", "Khartoum"),
    ("What is the capital of Tanzania?", "Dodoma"),
    ("What is the capital of Togo?", "Lome", "Lomé"),
    ("What is the capital of Tunisia?", "Tunis"),
    ("What is the capital of Uganda?", "Kampala"),
    ("What is the capital of Zambia?", "Lusaka"),
    ("What is the capital of Zimbabwe?", "Harare"),
]

EUROPE = [
    ("What is the capital of the United Kingdom?", "London"),
    ("What is the capital of Ireland?", "Dublin"),
    ("What is the capital of France?", "Paris"),
    ("What is the capital of Spain?", "Madrid"),
    ("What is the capital of Portugal?", "Lisbon"),
    ("What is the capital of Italy?", "Rome"),
    ("What is the capital of Greece?", "Athens"),
    ("What is the capital of Germany?", "Berlin"),
    ("What is the capital of Austria?", "Vienna"),
    ("What is the capital of Switzerland?", "Bern", "Berne"),
    ("What is the capital of the Netherlands?", "Amsterdam"),
    ("What is the capital of Belgium?", "Brussels"),
    ("What is the capital of Luxembourg?", "Luxembourg"),
    ("What is the capital of Denmark?", "Copenhagen"),
    ("What is the capital of Sweden?", "Stockholm"),
    ("What is the capital of Norway?", "Oslo"),
    ("What is the capital of Finland?", "Helsinki"),
    ("What is the capital of Iceland?", "Reykjavik", "Reykjavík"),
    ("What is the capital of Poland?", "Warsaw"),
    ("What is the capital of Czechia?", "Prague"),
    ("What is the capital of Slovakia?", "Bratislava"),
    ("What is the capital of Hungary?", "Budapest"),
    ("What is the capital of Romania?", "Bucharest"),
    ("What is the capital of Bulgaria?", "Sofia"),
    ("What is the capital of Serbia?", "Belgrade"),
    ("What is the capital of Croatia?", "Zagreb"),
    ("What is the capital of Slovenia?", "Ljubljana"),
    ("What is the capital of Bosnia and Herzegovina?", "Sarajevo"),
    ("What is the capital of Montenegro?", "Podgorica"),
    ("What is the capital of North Macedonia?", "Skopje"),
    ("What is the capital of Albania?", "Tirana"),
    ("What is the capital of Estonia?", "Tallinn"),
    ("What is the capital of Latvia?", "Riga"),
    ("What is the capital of Lithuania?", "Vilnius"),
    ("What is the capital of Belarus?", "Minsk"),
    ("What is the capital of Ukraine?", "Kyiv", "Kiev"),
    ("What is the capital of Moldova?", "Chisinau", "Chișinău", "Kishinev"),
    ("What is the capital of Malta?", "Valletta"),
    ("What is the capital of Cyprus?", "Nicosia"),
    ("What is the capital of Andorra?", "Andorra la Vella"),
    ("What is the capital of Monaco?", "Monaco"),
    ("What is the capital of San Marino?", "San Marino"),
    ("What is the capital of Liechtenstein?", "Vaduz"),
    ("What is the capital of Turkey?", "Ankara"),
]

ELEMENTS = [
    ("What is the chemical symbol for Hydrogen?", "H"),
    ("What is the chemical symbol for Helium?", "He"),
    ("What is the chemical symbol for Lithium?", "Li"),
    ("What is the chemical symbol for Beryllium?", "Be"),
    ("What is the chemical symbol for Boron?", "B"),
    ("What is the chemical symbol for Carbon?", "C"),
    ("What is the chemical symbol for Nitrogen?", "N"),
    ("What is the chemical symbol for Oxygen?", "O"),
    ("What is the chemical symbol for Fluorine?", "F"),
    ("What is the chemical symbol for Neon?", "Ne"),
    ("What is the chemical symbol for Sodium?", "Na"),
    ("What is the chemical symbol for Magnesium?", "Mg"),
    ("What is the chemical symbol for Aluminium?", "Al"),
    ("What is the chemical symbol for Silicon?", "Si"),
    ("What is the chemical symbol for Phosphorus?", "P"),
    ("What is the chemical symbol for Sulfur?", "S"),
    ("What is the chemical symbol for Chlorine?", "Cl"),
    ("What is the chemical symbol for Argon?", "Ar"),
    ("What is the chemical symbol for Potassium?", "K"),
    ("What is the chemical symbol for Calcium?", "Ca"),
    ("What is the chemical symbol for Iron?", "Fe"),
    ("What is the chemical symbol for Copper?", "Cu"),
    ("What is the chemical symbol for Zinc?", "Zn"),
    ("What is the chemical symbol for Silver?", "Ag"),
    ("What is the chemical symbol for Gold?", "Au"),
    ("What is the chemical symbol for Mercury?", "Hg"),
    ("What is the chemical symbol for Lead?", "Pb"),
    ("What is the chemical symbol for Uranium?", "U"),
    ("What element has the atomic number 1?", "Hydrogen"),
    ("What element has the atomic number 2?", "Helium"),
    ("What element has the atomic number 6?", "Carbon"),
    ("What element has the atomic number 8?", "Oxygen"),
    ("What element has the atomic number 11?", "Sodium"),
    ("What element has the atomic number 13?", "Aluminium", "Aluminum"),
    ("What element has the atomic number 26?", "Iron"),
    ("What element has the atomic number 29?", "Copper"),
    ("What element has the atomic number 47?", "Silver"),
    ("What element has the atomic number 79?", "Gold"),
    ("What element has the atomic number 80?", "Mercury"),
    ("What element has the atomic number 82?", "Lead"),
    ("What element has the atomic number 92?", "Uranium"),
]

ASIA = [
    ("What is the capital of Japan?", "Tokyo"),
    ("What is the capital of China?", "Beijing"),
    ("What is the capital of South Korea?", "Seoul"),
    ("What is the capital of North Korea?", "Pyongyang"),
    ("What is the capital of India?", "New Delhi"),
    ("What is the capital of Thailand?", "Bangkok"),
    ("What is the capital of Indonesia?", "Jakarta"),
    ("What is the capital of Vietnam?", "Hanoi"),
    ("What is the capital of the Philippines?", "Manila"),
    ("What is the capital of Malaysia?", "Kuala Lumpur"),
    ("What is the capital of Pakistan?", "Islamabad"),
    ("What is the capital of Bangladesh?", "Dhaka"),
    ("What is the capital of Sri Lanka?", "Colombo"),
    ("What is the capital of Nepal?", "Kathmandu"),
    ("What is the capital of Bhutan?", "Thimphu"),
    ("What is the capital of the Maldives?", "Male", "Malé"),
    ("What is the capital of Myanmar?", "Naypyidaw", "Nay Pyi Taw"),
    ("What is the capital of Laos?", "Vientiane"),
    ("What is the capital of Cambodia?", "Phnom Penh"),
    ("What is the capital of Singapore?", "Singapore"),
    ("What is the capital of Brunei?", "Bandar Seri Begawan"),
    ("What is the capital of Timor-Leste?", "Dili"),
    ("What is the capital of Turkey?", "Ankara"),
    ("What is the capital of Saudi Arabia?", "Riyadh"),
    ("What is the capital of Iran?", "Tehran"),
    ("What is the capital of Iraq?", "Baghdad"),
    ("What is the capital of Syria?", "Damascus"),
    ("What is the capital of Lebanon?", "Beirut"),
    ("What is the capital of Jordan?", "Amman"),
    ("What is the capital of Israel?", "Jerusalem"),
    ("What is the capital of the United Arab Emirates?", "Abu Dhabi"),
    ("What is the capital of Qatar?", "Doha"),
    ("What is the capital of Kuwait?", "Kuwait City"),
    ("What is the capital of Oman?", "Muscat"),
    ("What is the capital of Yemen?", "Sanaa", "Sana'a"),
    ("What is the capital of Afghanistan?", "Kabul"),
    ("What is the capital of Mongolia?", "Ulaanbaatar"),
    ("What is the capital of Kazakhstan?", "Astana"),
    ("What is the capital of Uzbekistan?", "Tashkent"),
    ("What is the capital of Kyrgyzstan?", "Bishkek"),
    ("What is the capital of Tajikistan?", "Dushanbe"),
    ("What is the capital of Turkmenistan?", "Ashgabat"),
    ("What is the capital of Azerbaijan?", "Baku"),
    ("What is the capital of Georgia?", "Tbilisi"),
    ("What is the capital of Armenia?", "Yerevan"),
    ("What is the capital of Taiwan?", "Taipei"),
]

US_STATES = [
    ("What is the capital of Alabama?", "Montgomery"),
    ("What is the capital of Alaska?", "Juneau"),
    ("What is the capital of Arizona?", "Phoenix"),
    ("What is the capital of Arkansas?", "Little Rock"),
    ("What is the capital of California?", "Sacramento"),
    ("What is the capital of Colorado?", "Denver"),
    ("What is the capital of Connecticut?", "Hartford"),
    ("What is the capital of Delaware?", "Dover"),
    ("What is the capital of Florida?", "Tallahassee"),
    ("What is the capital of Georgia (US state)?", "Atlanta"),
    ("What is the capital of Hawaii?", "Honolulu"),
    ("What is the capital of Idaho?", "Boise"),
    ("What is the capital of Illinois?", "Springfield"),
    ("What is the capital of Indiana?", "Indianapolis"),
    ("What is the capital of Iowa?", "Des Moines"),
    ("What is the capital of Kansas?", "Topeka"),
    ("What is the capital of Kentucky?", "Frankfort"),
    ("What is the capital of Louisiana?", "Baton Rouge"),
    ("What is the capital of Maine?", "Augusta"),
    ("What is the capital of Maryland?", "Annapolis"),
    ("What is the capital of Massachusetts?", "Boston"),
    ("What is the capital of Michigan?", "Lansing"),
    ("What is the capital of Minnesota?", "Saint Paul", "St. Paul"),
    ("What is the capital of Mississippi?", "Jackson"),
    ("What is the capital of Missouri?", "Jefferson City"),
    ("What is the capital of Montana?", "Helena"),
    ("What is the capital of Nebraska?", "Lincoln"),
    ("What is the capital of Nevada?", "Carson City"),
    ("What is the capital of New Hampshire?", "Concord"),
    ("What is the capital of New Jersey?", "Trenton"),
    ("What is the capital of New Mexico?", "Santa Fe"),
    ("What is the capital of New York?", "Albany"),
    ("What is the capital of North Carolina?", "Raleigh"),
    ("What is the capital of North Dakota?", "Bismarck"),
    ("What is the capital of Ohio?", "Columbus"),
    ("What is the capital of Oklahoma?", "Oklahoma City"),
    ("What is the capital of Oregon?", "Salem"),
    ("What is the capital of Pennsylvania?", "Harrisburg"),
    ("What is the capital of Rhode Island?", "Providence"),
    ("What is the capital of South Carolina?", "Columbia"),
    ("What is the capital of South Dakota?", "Pierre"),
    ("What is the capital of Tennessee?", "Nashville"),
    ("What is the capital of Texas?", "Austin"),
    ("What is the capital of Utah?", "Salt Lake City"),
    ("What is the capital of Vermont?", "Montpelier"),
    ("What is the capital of Virginia?", "Richmond"),
    ("What is the capital of Washington state?", "Olympia"),
    ("What is the capital of West Virginia?", "Charleston"),
    ("What is the capital of Wisconsin?", "Madison"),
    ("What is the capital of Wyoming?", "Cheyenne"),
]
AFRICA_LARGEST = [
    ("What is the largest city in Algeria?", "Algiers", "Algiers City"),
    ("What is the largest city in Angola?", "Luanda"),
    ("What is the largest city in Benin?", "Cotonou"),
    ("What is the largest city in Botswana?", "Gaborone"),
    ("What is the largest city in Burkina Faso?", "Ouagadougou"),
    ("What is the largest city in Burundi?", "Bujumbura", "Bujumbura City"),
    ("What is the largest city in Cape Verde?", "Praia"),
    ("What is the largest city in Cameroon?", "Douala"),
    ("What is the largest city in the Central African Republic?", "Bangui"),
    ("What is the largest city in Chad?", "NDjamena", "N'Djamena"),
    ("What is the largest city in Comoros?", "Moroni"),
    ("What is the largest city in the Democratic Republic of the Congo?", "Kinshasa"),
    ("What is the largest city in the Republic of the Congo?", "Brazzaville"),
    ("What is the largest city in Djibouti?", "Djibouti", "Djibouti City"),
    ("What is the largest city in Egypt?", "Cairo"),
    ("What is the largest city in Equatorial Guinea?", "Bata"),
    ("What is the largest city in Eritrea?", "Asmara"),
    ("What is the largest city in Eswatini?", "Manzini"),
    ("What is the largest city in Ethiopia?", "Addis Ababa"),
    ("What is the largest city in Gabon?", "Libreville"),
    ("What is the largest city in Gambia?", "Serekunda", "Serrekunda"),
    ("What is the largest city in Ghana?", "Accra"),
    ("What is the largest city in Guinea?", "Conakry"),
    ("What is the largest city in Guinea-Bissau?", "Bissau"),
    ("What is the largest city in Ivory Coast?", "Abidjan"),
    ("What is the largest city in Kenya?", "Nairobi"),
    ("What is the largest city in Lesotho?", "Maseru"),
    ("What is the largest city in Liberia?", "Monrovia"),
    ("What is the largest city in Libya?", "Tripoli"),
    ("What is the largest city in Madagascar?", "Antananarivo"),
    ("What is the largest city in Malawi?", "Lilongwe"),
    ("What is the largest city in Mali?", "Bamako"),
    ("What is the largest city in Mauritania?", "Nouakchott"),
    ("What is the largest city in Mauritius?", "Port Louis"),
    ("What is the largest city in Morocco?", "Casablanca"),
    ("What is the largest city in Mozambique?", "Maputo"),
    ("What is the largest city in Namibia?", "Windhoek"),
    ("What is the largest city in Niger?", "Niamey"),
    ("What is the largest city in Nigeria?", "Lagos"),
    ("What is the largest city in Rwanda?", "Kigali"),
    ("What is the largest city in Sao Tome and Principe?", "Sao Tome", "São Tomé"),
    ("What is the largest city in Senegal?", "Dakar"),
    ("What is the largest city in Seychelles?", "Victoria"),
    ("What is the largest city in Sierra Leone?", "Freetown"),
    ("What is the largest city in Somalia?", "Mogadishu"),
    ("What is the largest city in South Africa?", "Johannesburg"),
    ("What is the largest city in South Sudan?", "Juba"),
    ("What is the largest city in Sudan?", "Khartoum"),
    ("What is the largest city in Tanzania?", "Dar es Salaam", "Dar Es Salaam", "Dar es-Salaam"),
    ("What is the largest city in Togo?", "Lome", "Lomé"),
    ("What is the largest city in Tunisia?", "Tunis"),
    ("What is the largest city in Uganda?", "Kampala"),
    ("What is the largest city in Zambia?", "Lusaka"),
    ("What is the largest city in Zimbabwe?", "Harare"),
]

WORLD_CAP_TRAPS = [
    ("What is the capital of Australia?", "Canberra"),
    ("What is the capital of Canada?", "Ottawa"),
    ("What is the capital of Brazil?", "Brasilia", "Brasília"),
    ("What is the capital of Turkey?", "Ankara"),
    ("What is the capital of Switzerland?", "Bern", "Berne"),
    ("What is the capital of Vietnam?", "Hanoi"),
    ("What is the capital of Kazakhstan?", "Astana"),
    ("What is the capital of India?", "New Delhi", "Delhi"),
    ("What is the capital of Pakistan?", "Islamabad"),
    ("What is the capital of Myanmar?", "Naypyidaw", "Nay Pyi Taw"),
    ("What is the capital of Sri Lanka?", "Sri Jayawardenepura Kotte", "Kotte"),
    ("What is the capital of Belize?", "Belmopan"),
    ("What is the capital of Bolivia?", "Sucre", "La Paz"),
    ("What is the capital of Ivory Coast?", "Yamoussoukro"),
    ("What is the capital of the Netherlands?", "Amsterdam"),
    ("What is the capital of Morocco?", "Rabat"),
    ("What is the capital of Nigeria?", "Abuja"),
    ("What is the capital of Tanzania?", "Dodoma"),
    ("What is the capital of Benin?", "Porto-Novo", "Porto Novo"),
    ("What is the capital of Equatorial Guinea?", "Malabo"),
    ("What is the capital of Gambia?", "Banjul"),
    ("What is the capital of the United States?", "Washington, D.C.", "Washington DC", "Washington"),
    ("What is the capital of China?", "Beijing"),
    ("What is the capital of South Africa?", "Pretoria", "Cape Town", "Bloemfontein"),
    ("What is the capital of New Zealand?", "Wellington"),
    ("What is the capital of Ecuador?", "Quito"),
    ("What is the capital of Yemen?", "Sanaa", "Sana'a"),
    ("What is the capital of Israel?", "Jerusalem"),
    ("What is the capital of the United Arab Emirates?", "Abu Dhabi"),
    ("What is the capital of Cameroon?", "Yaounde", "Yaoundé"),
    ("What is the capital of Burundi?", "Gitega"),
    ("What is the capital of Malawi?", "Lilongwe"),
    ("What is the capital of Eswatini?", "Mbabane"),
    ("What is the capital of Brunei?", "Bandar Seri Begawan"),
    ("What is the capital of Laos?", "Vientiane"),
    ("What is the capital of Moldova?", "Chisinau", "Chișinău"),
    ("What is the capital of Belarus?", "Minsk"),
    ("What is the capital of Ukraine?", "Kyiv", "Kiev"),
    ("What is the capital of Georgia?", "Tbilisi"),
    ("What is the capital of Armenia?", "Yerevan"),
    ("What is the capital of Azerbaijan?", "Baku"),
    ("What is the capital of Turkmenistan?", "Ashgabat"),
    ("What is the capital of Tajikistan?", "Dushanbe"),
    ("What is the capital of Kyrgyzstan?", "Bishkek"),
    ("What is the capital of Uzbekistan?", "Tashkent"),
    ("What is the capital of Mongolia?", "Ulaanbaatar"),
    ("What is the capital of Afghanistan?", "Kabul"),
    ("What is the capital of Iran?", "Tehran"),
    ("What is the capital of Iraq?", "Baghdad"),
    ("What is the capital of Saudi Arabia?", "Riyadh"),
    ("What is the capital of Qatar?", "Doha"),
    ("What is the capital of Oman?", "Muscat"),
    ("What is the capital of Jordan?", "Amman"),
    ("What is the capital of Lebanon?", "Beirut"),
    ("What is the capital of Syria?", "Damascus"),
    ("What is the capital of Kuwait?", "Kuwait City", "Kuwait"),
    ("What is the capital of Bahrain?", "Manama"),
    ("What is the capital of Cyprus?", "Nicosia"),
    ("What is the capital of Malta?", "Valletta"),
    ("What is the capital of Andorra?", "Andorra la Vella"),
    ("What is the capital of Liechtenstein?", "Vaduz"),
    ("What is the capital of San Marino?", "San Marino"),
    ("What is the capital of Monaco?", "Monaco"),
    ("What is the capital of Luxembourg?", "Luxembourg"),
    ("What is the capital of Vatican City?", "Vatican City", "Vatican"),
    ("What is the capital of Paraguay?", "Asuncion", "Asunción"),
    ("What is the capital of Uruguay?", "Montevideo"),
    ("What is the capital of Suriname?", "Paramaribo"),
    ("What is the capital of Guyana?", "Georgetown"),
    ("What is the capital of Haiti?", "Port-au-Prince", "Port au Prince"),
    ("What is the capital of Jamaica?", "Kingston"),
    ("What is the capital of Trinidad and Tobago?", "Port of Spain", "Port-of-Spain"),
    ("What is the capital of the Bahamas?", "Nassau"),
    ("What is the capital of Barbados?", "Bridgetown"),
    ("What is the capital of Grenada?", "Saint George's", "St. George's"),
    ("What is the capital of Saint Lucia?", "Castries"),
    ("What is the capital of Dominica?", "Roseau"),
    ("What is the capital of Saint Vincent and the Grenadines?", "Kingstown"),
    ("What is the capital of Antigua and Barbuda?", "Saint John's", "St. John's"),
    ("What is the capital of Saint Kitts and Nevis?", "Basseterre"),
    ("What is the capital of Guatemala?", "Guatemala City"),
    ("What is the capital of Honduras?", "Tegucigalpa"),
    ("What is the capital of Nicaragua?", "Managua"),
    ("What is the capital of Costa Rica?", "San Jose", "San José"),
    ("What is the capital of Panama?", "Panama City"),
    ("What is the capital of El Salvador?", "San Salvador"),
    ("What is the capital of Cuba?", "Havana"),
    ("What is the capital of the Dominican Republic?", "Santo Domingo"),
    ("What is the capital of Fiji?", "Suva"),
    ("What is the capital of Vanuatu?", "Port Vila"),
    ("What is the capital of Samoa?", "Apia"),
    ("What is the capital of the Solomon Islands?", "Honiara"),
    ("What is the capital of Tonga?", "Nuku'alofa", "Nukualofa"),
    ("What is the capital of Kiribati?", "Tarawa", "South Tarawa"),
    ("What is the capital of Tuvalu?", "Funafuti"),
    ("What is the capital of Nauru?", "Yaren"),
    ("What is the capital of Palau?", "Ngerulmud", "Melekeok"),
    ("What is the capital of the Federated States of Micronesia?", "Palikir"),
    ("What is the capital of the Marshall Islands?", "Majuro"),
    ("What is the capital of Papua New Guinea?", "Port Moresby"),
    ("What is the capital of Timor-Leste?", "Dili"),
    ("What is the capital of Taiwan?", "Taipei"),
    ("What is the capital of Kosovo?", "Pristina", "Priština"),
    ("What is the capital of Montenegro?", "Podgorica"),
    ("What is the capital of Bosnia and Herzegovina?", "Sarajevo"),
    ("What is the capital of North Macedonia?", "Skopje"),
    ("What is the capital of Western Sahara?", "Laayoune", "El Aaiún", "Laayoune"),
    ("What is the capital of Seychelles?", "Victoria"),
    ("What is the capital of Comoros?", "Moroni"),
    ("What is the capital of Mauritius?", "Port Louis"),
    ("What is the capital of Cape Verde?", "Praia"),
    ("What is the capital of Sao Tome and Principe?", "Sao Tome", "São Tomé"),
    ("What is the capital of Djibouti?", "Djibouti City", "Djibouti"),
    ("What is the capital of Eritrea?", "Asmara"),
    ("What is the capital of Chad?", "NDjamena", "N'Djamena"),
    ("What is the capital of Niger?", "Niamey"),
    ("What is the capital of Mali?", "Bamako"),
    ("What is the capital of Burkina Faso?", "Ouagadougou"),
    ("What is the capital of Mauritania?", "Nouakchott"),
    ("What is the capital of Guinea?", "Conakry"),
    ("What is the capital of Sierra Leone?", "Freetown"),
    ("What is the capital of Liberia?", "Monrovia"),
    ("What is the capital of Togo?", "Lome", "Lomé"),
    ("What is the capital of Gabon?", "Libreville"),
    ("What is the capital of the Republic of the Congo?", "Brazzaville"),
    ("What is the capital of the Central African Republic?", "Bangui"),
    ("What is the capital of Madagascar?", "Antananarivo"),
    ("What is the capital of Zambia?", "Lusaka"),
    ("What is the capital of Zimbabwe?", "Harare"),
    ("What is the capital of Botswana?", "Gaborone"),
    ("What is the capital of Namibia?", "Windhoek"),
    ("What is the capital of Rwanda?", "Kigali"),
    ("What is the capital of Uganda?", "Kampala"),
    ("What is the capital of Lesotho?", "Maseru"),
]

WORLD_LARGEST = [
    ("What is the largest city in Australia?", "Sydney"),
    ("What is the largest city in Canada?", "Toronto"),
    ("What is the largest city in the United States?", "New York City", "New York"),
    ("What is the largest city in Brazil?", "Sao Paulo", "São Paulo"),
    ("What is the largest city in China?", "Shanghai"),
    ("What is the largest city in India?", "Mumbai"),
    ("What is the largest city in Pakistan?", "Karachi"),
    ("What is the largest city in Turkey?", "Istanbul"),
    ("What is the largest city in New Zealand?", "Auckland"),
    ("What is the largest city in Switzerland?", "Zurich", "Zürich"),
    ("What is the largest city in Myanmar?", "Yangon"),
    ("What is the largest city in Vietnam?", "Ho Chi Minh City"),
    ("What is the largest city in Sri Lanka?", "Colombo"),
    ("What is the largest city in Kazakhstan?", "Almaty"),
    ("What is the largest city in Ecuador?", "Guayaquil"),
    ("What is the largest city in Bolivia?", "Santa Cruz de la Sierra", "Santa Cruz"),
    ("What is the largest city in Russia?", "Moscow"),
    ("What is the largest city in Ukraine?", "Kyiv", "Kiev"),
    ("What is the largest city in Poland?", "Warsaw"),
    ("What is the largest city in Romania?", "Bucharest"),
    ("What is the largest city in Hungary?", "Budapest"),
    ("What is the largest city in Bulgaria?", "Sofia"),
    ("What is the largest city in Greece?", "Athens"),
    ("What is the largest city in Spain?", "Madrid"),
    ("What is the largest city in Portugal?", "Lisbon"),
    ("What is the largest city in Italy?", "Rome"),
    ("What is the largest city in France?", "Paris"),
    ("What is the largest city in Germany?", "Berlin"),
    ("What is the largest city in the United Kingdom?", "London"),
    ("What is the largest city in Ireland?", "Dublin"),
    ("What is the largest city in the Netherlands?", "Amsterdam"),
    ("What is the largest city in Belgium?", "Brussels"),
    ("What is the largest city in Austria?", "Vienna"),
    ("What is the largest city in Czechia?", "Prague"),
    ("What is the largest city in Sweden?", "Stockholm"),
    ("What is the largest city in Norway?", "Oslo"),
    ("What is the largest city in Denmark?", "Copenhagen"),
    ("What is the largest city in Finland?", "Helsinki"),
    ("What is the largest city in Iceland?", "Reykjavik", "Reykjavík"),
    ("What is the largest city in Estonia?", "Tallinn"),
    ("What is the largest city in Latvia?", "Riga"),
    ("What is the largest city in Lithuania?", "Vilnius"),
    ("What is the largest city in Belarus?", "Minsk"),
    ("What is the largest city in Moldova?", "Chisinau", "Chișinău"),
    ("What is the largest city in Armenia?", "Yerevan"),
    ("What is the largest city in Georgia?", "Tbilisi"),
    ("What is the largest city in Azerbaijan?", "Baku"),
    ("What is the largest city in Turkmenistan?", "Ashgabat"),
    ("What is the largest city in Uzbekistan?", "Tashkent"),
    ("What is the largest city in Kyrgyzstan?", "Bishkek"),
    ("What is the largest city in Tajikistan?", "Dushanbe"),
    ("What is the largest city in Mongolia?", "Ulaanbaatar"),
    ("What is the largest city in Afghanistan?", "Kabul"),
    ("What is the largest city in Iran?", "Tehran"),
    ("What is the largest city in Iraq?", "Baghdad"),
    ("What is the largest city in Saudi Arabia?", "Riyadh"),
    ("What is the largest city in Qatar?", "Doha"),
    ("What is the largest city in Oman?", "Muscat"),
    ("What is the largest city in Jordan?", "Amman"),
    ("What is the largest city in Lebanon?", "Beirut"),
    ("What is the largest city in Syria?", "Aleppo"),
    ("What is the largest city in Yemen?", "Sanaa", "Sana'a"),
    ("What is the largest city in Kuwait?", "Kuwait City", "Kuwait"),
    ("What is the largest city in Bahrain?", "Manama"),
    ("What is the largest city in Cyprus?", "Nicosia"),
    ("What is the largest city in Israel?", "Jerusalem", "Tel Aviv"),
    ("What is the largest city in the United Arab Emirates?", "Dubai"),
    ("What is the largest city in Bangladesh?", "Dhaka"),
    ("What is the largest city in Nepal?", "Kathmandu"),
    ("What is the largest city in Bhutan?", "Thimphu"),
    ("What is the largest city in the Maldives?", "Male", "Malé"),
    ("What is the largest city in Laos?", "Vientiane"),
    ("What is the largest city in Cambodia?", "Phnom Penh"),
    ("What is the largest city in Thailand?", "Bangkok"),
    ("What is the largest city in Malaysia?", "Kuala Lumpur"),
    ("What is the largest city in Singapore?", "Singapore"),
    ("What is the largest city in Indonesia?", "Jakarta"),
    ("What is the largest city in the Philippines?", "Quezon City", "Manila"),
    ("What is the largest city in Brunei?", "Bandar Seri Begawan"),
    ("What is the largest city in Timor-Leste?", "Dili"),
    ("What is the largest city in Papua New Guinea?", "Port Moresby"),
    ("What is the largest city in Fiji?", "Suva"),
    ("What is the largest city in New Caledonia?", "Noumea", "Nouméa"),
    ("What is the largest city in French Polynesia?", "Papeete"),
    ("What is the largest city in Vanuatu?", "Port Vila"),
    ("What is the largest city in Samoa?", "Apia"),
    ("What is the largest city in the Solomon Islands?", "Honiara"),
    ("What is the largest city in Tonga?", "Nuku'alofa", "Nukualofa"),
    ("What is the largest city in Kiribati?", "Tarawa", "South Tarawa"),
    ("What is the largest city in Tuvalu?", "Funafuti"),
    ("What is the largest city in Nauru?", "Yaren"),
    ("What is the largest city in the Marshall Islands?", "Majuro"),
    ("What is the largest city in Micronesia?", "Palikir"),
    ("What is the largest city in Palau?", "Koror", "Ngerulmud"),
    ("What is the largest city in Taiwan?", "New Taipei", "Taipei"),
    ("What is the largest city in South Korea?", "Seoul"),
    ("What is the largest city in North Korea?", "Pyongyang"),
    ("What is the largest city in Japan?", "Tokyo"),
    ("What is the largest city in Mexico?", "Mexico City"),
    ("What is the largest city in Guatemala?", "Guatemala City"),
    ("What is the largest city in Belize?", "Belize City"),
    ("What is the largest city in Honduras?", "Tegucigalpa"),
    ("What is the largest city in El Salvador?", "San Salvador"),
    ("What is the largest city in Nicaragua?", "Managua"),
    ("What is the largest city in Costa Rica?", "San Jose", "San José"),
    ("What is the largest city in Panama?", "Panama City"),
    ("What is the largest city in Cuba?", "Havana"),
    ("What is the largest city in Jamaica?", "Kingston"),
    ("What is the largest city in Haiti?", "Port-au-Prince", "Port au Prince"),
    ("What is the largest city in the Dominican Republic?", "Santo Domingo"),
    ("What is the largest city in Trinidad and Tobago?", "Port of Spain", "Port-of-Spain"),
    ("What is the largest city in the Bahamas?", "Nassau"),
    ("What is the largest city in Barbados?", "Bridgetown"),
    ("What is the largest city in Argentina?", "Buenos Aires"),
    ("What is the largest city in Colombia?", "Bogota", "Bogotá"),
    ("What is the largest city in Venezuela?", "Caracas"),
    ("What is the largest city in Peru?", "Lima"),
    ("What is the largest city in Chile?", "Santiago", "Santiago de Chile"),
    ("What is the largest city in Paraguay?", "Asuncion", "Asunción"),
    ("What is the largest city in Uruguay?", "Montevideo"),
    ("What is the largest city in Suriname?", "Paramaribo"),
    ("What is the largest city in Guyana?", "Georgetown"),
    ("What is the largest city in Algeria?", "Algiers"),
    ("What is the largest city in Libya?", "Tripoli"),
    ("What is the largest city in Tunisia?", "Tunis"),
    ("What is the largest city in Egypt?", "Cairo"),
    ("What is the largest city in Morocco?", "Casablanca"),
    ("What is the largest city in Western Sahara?", "Laayoune", "El Aaiún"),
    ("What is the largest city in Ethiopia?", "Addis Ababa"),
    ("What is the largest city in Kenya?", "Nairobi"),
    ("What is the largest city in Ghana?", "Accra"),
    ("What is the largest city in Cameroon?", "Douala"),
    ("What is the largest city in Gabon?", "Libreville"),
    ("What is the largest city in the Republic of the Congo?", "Brazzaville"),
    ("What is the largest city in the Democratic Republic of the Congo?", "Kinshasa"),
    ("What is the largest city in Madagascar?", "Antananarivo"),
    ("What is the largest city in Mozambique?", "Maputo"),
    ("What is the largest city in Angola?", "Luanda"),
    ("What is the largest city in Zambia?", "Lusaka"),
    ("What is the largest city in Zimbabwe?", "Harare"),
    ("What is the largest city in Botswana?", "Gaborone"),
    ("What is the largest city in Namibia?", "Windhoek"),
    ("What is the largest city in Malawi?", "Blantyre", "Lilongwe"),
    ("What is the largest city in Burundi?", "Bujumbura"),
    ("What is the largest city in Rwanda?", "Kigali"),
    ("What is the largest city in Uganda?", "Kampala"),
    ("What is the largest city in Somalia?", "Mogadishu"),
    ("What is the largest city in Djibouti?", "Djibouti City", "Djibouti"),
    ("What is the largest city in Eritrea?", "Asmara"),
    ("What is the largest city in Sudan?", "Khartoum", "Omdurman"),
    ("What is the largest city in South Sudan?", "Juba"),
    ("What is the largest city in Chad?", "NDjamena", "N'Djamena"),
    ("What is the largest city in Niger?", "Niamey"),
    ("What is the largest city in Mali?", "Bamako"),
    ("What is the largest city in Burkina Faso?", "Ouagadougou"),
    ("What is the largest city in Senegal?", "Dakar"),
    ("What is the largest city in Mauritania?", "Nouakchott"),
    ("What is the largest city in Guinea?", "Conakry"),
    ("What is the largest city in Sierra Leone?", "Freetown"),
    ("What is the largest city in Liberia?", "Monrovia"),
    ("What is the largest city in Togo?", "Lome", "Lomé"),
    ("What is the largest city in Benin?", "Cotonou"),
    ("What is the largest city in Ivory Coast?", "Abidjan"),
    ("What is the largest city in Equatorial Guinea?", "Bata"),
    ("What is the largest city in Gambia?", "Serekunda", "Serrekunda"),
    ("What is the largest city in Eswatini?", "Manzini"),
    ("What is the largest city in Lesotho?", "Maseru"),
    ("What is the largest city in Seychelles?", "Victoria"),
    ("What is the largest city in Comoros?", "Moroni"),
    ("What is the largest city in Mauritius?", "Port Louis"),
    ("What is the largest city in Cape Verde?", "Praia"),
    ("What is the largest city in Sao Tome and Principe?", "Sao Tome", "São Tomé"),
    ("What is the largest city in Greenland?", "Nuuk"),
]

WORLD_TRICKY = [
    ("What is the capital of Australia?", "Canberra", "Australian Capital Territory"),
    ("What is the capital of Canada?", "Ottawa"),
    ("What is the capital of Brazil?", "Brasilia", "Brasília"),
    ("What is the capital of Turkey?", "Ankara"),
    ("What is the capital of Switzerland?", "Bern", "Berne"),
    ("What is the capital of Vietnam?", "Hanoi"),
    ("What is the capital of Kazakhstan?", "Astana"),
    ("What is the capital of India?", "New Delhi", "Delhi"),
    ("What is the capital of Pakistan?", "Islamabad"),
    ("What is the capital of Ivory Coast?", "Yamoussoukro"),
    ("What is the capital of Myanmar?", "Naypyidaw", "Nay Pyi Taw"),
    ("What is the capital of Sri Lanka?", "Sri Jayawardenepura Kotte", "Kotte", "Sri Jayawardenapura Kotte"),
    ("What is the capital of Belize?", "Belmopan"),
    ("What is the capital of Bolivia?", "Sucre"),
    ("What is the capital of Benin?", "Porto-Novo", "Porto Novo"),
    ("What is the capital of Ecuador?", "Quito"),
    ("What is the capital of Peru?", "Lima"),
    ("What is the capital of Colombia?", "Bogota", "Bogotá"),
    ("What is the capital of Chile?", "Santiago", "Santiago de Chile"),
    ("What is the capital of Argentina?", "Buenos Aires"),
    ("What is the capital of the Netherlands?", "Amsterdam"),
    ("What is the capital of Israel?", "Jerusalem"),
    ("What is the capital of Jordan?", "Amman"),
    ("What is the capital of Saudi Arabia?", "Riyadh"),
    ("What is the capital of the United Arab Emirates?", "Abu Dhabi"),
    ("What is the capital of Qatar?", "Doha"),
    ("What is the capital of Kuwait?", "Kuwait City", "Kuwait"),
    ("What is the capital of Oman?", "Muscat"),
    ("What is the capital of Ukraine?", "Kyiv", "Kiev"),
    ("What is the capital of Poland?", "Warsaw"),
    ("What is the capital of Hungary?", "Budapest"),
    ("What is the capital of Romania?", "Bucharest"),
    ("What is the capital of Bulgaria?", "Sofia"),
    ("What is the capital of Greece?", "Athens"),
    ("What is the capital of Albania?", "Tirana"),
    ("What is the capital of Kosovo?", "Pristina", "Priština"),
    ("What is the capital of Serbia?", "Belgrade"),
    ("What is the capital of Montenegro?", "Podgorica"),
    ("What is the capital of North Macedonia?", "Skopje"),
    ("What is the capital of Bosnia and Herzegovina?", "Sarajevo"),
    ("What is the capital of Croatia?", "Zagreb"),
    ("What is the capital of Slovenia?", "Ljubljana"),
    ("What is the capital of Latvia?", "Riga"),
    ("What is the capital of Lithuania?", "Vilnius"),
    ("What is the capital of Estonia?", "Tallinn"),
    ("What is the capital of Belarus?", "Minsk"),
    ("What is the capital of Moldova?", "Chisinau", "Chișinău"),
    ("What is the capital of Cyprus?", "Nicosia"),
    ("What is the capital of Malta?", "Valletta"),
]
